class FollowRecordAlreadyExistsError(Exception):
    pass

class FollowRecordNotFoundError(Exception):
    pass